version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    networks:
      - legalnet

  legal-qa-app:
    build: .
    container_name: legal-qa-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - elasticsearch
    networks:
      - legalnet

networks:
  legalnet:
    driver: bridge
